# translations.py – Syfer Grade Calculator
# Supported languages: French (fr), English (en), Italian (it)

TRANSLATIONS = {
    "fr": {
        "page_title":        "Syfer – Calculateur de notes",
        "app_title":         "📊 Syfer – Calculateur de notes",
        "subtitle":          "Entrez vos notes pour chaque matière. Toutes les notes sont **sur 20**.",
        "select_language":   "🌐 Langue / Language / Lingua",
        "name_label":        "Votre prénom",
        "name_placeholder":  "Entrez votre prénom",
        "section_marks":     "📝 Entrez vos notes",
        "coef_label":        "coef",
        "btn_calculate":     "Calculer mes résultats 🎯",
        "warn_name":         "Veuillez entrer votre prénom.",
        "results_for":       "Résultats de",
        "breakdown_title":   "#### Détail des notes",
        "col_subject":       "Matière",
        "col_mark":          "Note /20",
        "col_coef":          "Coef",
        "col_weighted":      "Pondérée",
        "metric_total":      "Total (pondéré)",
        "metric_average":    "Moyenne /20",
        "metric_coef":       "Coefficient total",
        "progress_label":    "Score global",
        "pass_msg":          "🎉 Félicitations {name} ! Vous avez réussi avec un total de **{total}** points (moyenne **{avg}/20**).",
        "fail_msg":          "📉 Pas encore, {name}. Votre total est de **{total}** points (moyenne **{avg}/20**). Courage, vous pouvez faire mieux !",
        "perf_title":        "#### Performance par matière",
        "perf_good":         "🟢 Bien",
        "perf_avg":          "🟡 Moyen",
        "perf_bad":          "🔴 À améliorer",
        "subjects": [
            ("Mathématiques",      5),
            ("Physique",           3),
            ("Informatique",       3),
            ("Maths supplémentaires", 3),
            ("Biologie",           3),
            ("Économie",           3),
            ("Géographie",         3),
            ("Chimie",             3),
        ],
    },

    "en": {
        "page_title":        "Syfer – Grade Calculator",
        "app_title":         "📊 Syfer – Grade Calculator",
        "subtitle":          "Enter your marks for each subject. All marks are **out of 20**.",
        "select_language":   "🌐 Langue / Language / Lingua",
        "name_label":        "Your name",
        "name_placeholder":  "Enter your name",
        "section_marks":     "📝 Enter your marks",
        "coef_label":        "coef",
        "btn_calculate":     "Calculate my results 🎯",
        "warn_name":         "Please enter your name first.",
        "results_for":       "Results for",
        "breakdown_title":   "#### Score breakdown",
        "col_subject":       "Subject",
        "col_mark":          "Mark /20",
        "col_coef":          "Coef",
        "col_weighted":      "Weighted",
        "metric_total":      "Total (weighted)",
        "metric_average":    "Average /20",
        "metric_coef":       "Total coefficient",
        "progress_label":    "Overall score",
        "pass_msg":          "🎉 Congratulations {name}! You passed with a total of **{total}** points (average **{avg}/20**).",
        "fail_msg":          "📉 Not there yet, {name}. Your total is **{total}** points (average **{avg}/20**). Keep working — you can do better!",
        "perf_title":        "#### Subject performance",
        "perf_good":         "🟢 Good",
        "perf_avg":          "🟡 Average",
        "perf_bad":          "🔴 Needs work",
        "subjects": [
            ("Mathematics",      5),
            ("Physics",          3),
            ("Computer Science", 3),
            ("Additional Math",  3),
            ("Biology",          3),
            ("Economics",        3),
            ("Geography",        3),
            ("Chemistry",        3),
        ],
    },

    "it": {
        "page_title":        "Syfer – Calcolatore di voti",
        "app_title":         "📊 Syfer – Calcolatore di voti",
        "subtitle":          "Inserisci i tuoi voti per ogni materia. Tutti i voti sono **su 20**.",
        "select_language":   "🌐 Langue / Language / Lingua",
        "name_label":        "Il tuo nome",
        "name_placeholder":  "Inserisci il tuo nome",
        "section_marks":     "📝 Inserisci i tuoi voti",
        "coef_label":        "coef",
        "btn_calculate":     "Calcola i miei risultati 🎯",
        "warn_name":         "Per favore inserisci il tuo nome.",
        "results_for":       "Risultati di",
        "breakdown_title":   "#### Dettaglio dei voti",
        "col_subject":       "Materia",
        "col_mark":          "Voto /20",
        "col_coef":          "Coef",
        "col_weighted":      "Ponderato",
        "metric_total":      "Totale (ponderato)",
        "metric_average":    "Media /20",
        "metric_coef":       "Coefficiente totale",
        "progress_label":    "Punteggio globale",
        "pass_msg":          "🎉 Complimenti {name}! Hai superato con un totale di **{total}** punti (media **{avg}/20**).",
        "fail_msg":          "📉 Non ancora, {name}. Il tuo totale è di **{total}** punti (media **{avg}/20**). Continua così, puoi fare meglio!",
        "perf_title":        "#### Prestazione per materia",
        "perf_good":         "🟢 Ottimo",
        "perf_avg":          "🟡 Sufficiente",
        "perf_bad":          "🔴 Da migliorare",
        "subjects": [
            ("Matematica",           5),
            ("Fisica",               3),
            ("Informatica",          3),
            ("Matematica avanzata",  3),
            ("Biologia",             3),
            ("Economia",             3),
            ("Geografia",            3),
            ("Chimica",              3),
        ],
    },
